# levels.py
# MicroPython-compatible platformer levels.
# Generated by tools/screen_editor.py.
#
# Tile key:  ' '=sky  '#'=platform  'H'=hazard  'C'=coin  'X'=exit  'S'=spawn
# scroll=0   normal platformer (walk + jump)
# scroll>0   auto-scroll / Geometry Dash mode (jump only), value = px/s

LEVELS = (
    {
        'rows': (
            '            ',
            '            ',
            '            ',
            '            ',
            '     ##     ',
            '  ##    ##  ',
            'S          X',
            '##H#H##H#H##',
        ),
    },
    {
        'rows': (
            '                                    ',
            '    C                      C        ',
            '   ###    ###        ###   ###      ',
            '       ###    H  ##             ##  ',
            '## ##       ##  ###     ###   ##    ',
            '   ## ###  ##     ## ###    ##    # ',
            'S   ## ##     H## ###   H##  ##  # X',
            '###H######H####H####H####H####H#####',
        ),
    },
    {
        'rows': (
            '                                    ',
            '                                    ',
            '       C   C                        ',
            '                                    ',
            '      ### ###           ###         ',
            '  ###             ###               ',
            'S    H   H   ###             H  H  X',
            '####################################',
        ),
    },
)
