#!/usr/bin/env python3
# tools/screen_editor.py
# Desktop-only level editor for the Platformer game.
# Requires: pip install pygame
#
# Usage:
#   python tools/screen_editor.py                                             # edit built-in levels.py
#   python tools/screen_editor.py --file games/platformer/custom_world1.py   # create custom campaign
#   python tools/screen_editor.py --file games/platformer/custom_world1.py --level 2
#
# Custom campaign files must be named custom_*.py inside games/platformer/ so
# that they are gitignored (private to your machine) but still importable by
# MicroPython on the Pico.  The CAMPAIGNS panel registers them for deployment.
#
# The CAMPAIGNS panel manages which level files appear in the on-device launcher
# carousel. Changes are written to:
#   games/platformer/campaigns.py  — read by the launcher on hardware
#   deploy.sh                      — controls which files are copied to the Pico
#
# Controls (edit mode):
#   Left-click / drag        — paint selected tile
#   Right-click / drag       — erase (paint ' ')
#   Scroll wheel             — scroll level horizontally
#   1-6                      — select tile from palette
#   S                        — save levels file
#   Left/Right arrow         — scroll level one column
#   PgUp / PgDn              — previous / next level

import sys
import os
import shutil

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _REPO_ROOT)

import pygame

# ── Layout ────────────────────────────────────────────────────────────────────
CELL    = 48
COLS    = 12
ROWS    = 8

PANEL_W = 164
TOP_H   = 50
GRID_Y  = TOP_H
WIN_W   = COLS * CELL + PANEL_W
WIN_H   = TOP_H + ROWS * CELL + 80

LVL_W_DEFAULT = 36

# ── Tile definitions ──────────────────────────────────────────────────────────
TILES = [
    (' ', 'Sky',      (  5,   5,  30)),
    ('#', 'Platform', ( 50,  50,  80)),
    ('H', 'Hazard',   (200,   0,   0)),
    ('C', 'Coin',     (255, 200,   0)),
    ('X', 'Exit',     (  0, 200, 220)),
    ('S', 'Spawn',    (200, 200, 200)),
]
TILE_CHARS = [t[0] for t in TILES]

# ── Colour palette for campaigns ──────────────────────────────────────────────
DEPLOY_PALETTE = [
    ('MAGENTA', (255,   0, 200)),
    ('CYAN',    (  0, 220, 255)),
    ('YELLOW',  (255, 200,   0)),
    ('GREEN',   (  0, 200,   0)),
    ('ORANGE',  (255, 100,   0)),
    ('PURPLE',  (160,   0, 255)),
    ('RED',     (255,   0,   0)),
]

# ── UI colours ────────────────────────────────────────────────────────────────
GRID_BG   = (10,  10,  10)
GRID_LINE = (30,  30,  50)
PANEL_BG  = (18,  18,  30)
DEPLOY_BG = ( 8,   8,  22)
TEXT_C    = (200, 200, 200)
DIM_C     = (70,  70, 100)
WARN_C    = (255,  80,  80)
OK_C      = ( 80, 220,  80)

BTN_C     = (45,  45,  75)
BTN_HV    = (75,  75, 120)
BTN_ACT   = (100, 70, 200)
BTN_SAVE  = (30, 110,  50)
BTN_SAV_H = (50, 150,  70)
BTN_DEL   = (130, 35,  35)
BTN_DEL_H = (170, 55,  55)
BTN_ADD   = (35, 110,  55)
BTN_ADD_H = (55, 150,  75)
BTN_REM   = (110, 60,  25)
BTN_REM_H = (150, 90,  40)
BTN_SPD   = (60,  40, 110)
BTN_SPD_H = (90,  60, 160)
BTN_DEP   = (40,  90, 160)
BTN_DEP_H = (60, 130, 210)
HOVER_BDR = (180, 180,  60)
SEL_BDR   = (255, 255,  60)
SCROLL_HI = (255, 140,   0)

# ── Paths ─────────────────────────────────────────────────────────────────────
DEFAULT_LEVELS_PATH = os.path.join(_REPO_ROOT, 'games', 'platformer', 'levels.py')
CAMPAIGNS_PATH      = os.path.join(_REPO_ROOT, 'games', 'platformer', 'campaigns.py')
DEPLOY_SH_PATH      = os.path.join(_REPO_ROOT, 'deploy.sh')
PLATFORMER_DIR      = os.path.join(_REPO_ROOT, 'games', 'platformer')


# ── File I/O — levels ─────────────────────────────────────────────────────────

def load_levels_from_file(path):
    if not os.path.exists(path):
        return [blank_level()]
    with open(path) as f:
        src = f.read()
    ns = {}
    exec(src, ns)
    result = []
    for lv in ns.get('LEVELS', ()):
        result.append({'rows': [list(row) for row in lv['rows']],
                       'scroll': lv.get('scroll', 0)})
    return result or [blank_level()]


def save_levels_to_file(levels, path):
    lines = [
        "# " + os.path.basename(path),
        "# MicroPython-compatible platformer levels.",
        "# Generated by tools/screen_editor.py.",
        "#",
        "# Tile key:  ' '=sky  '#'=platform  'H'=hazard  'C'=coin  'X'=exit  'S'=spawn",
        "# scroll=0   normal platformer (walk + jump)",
        "# scroll>0   auto-scroll / Geometry Dash mode (jump only), value = px/s",
        "",
        "LEVELS = (",
    ]
    for lv in levels:
        lines.append("    {")
        if lv['scroll']:
            lines.append("        'scroll': " + str(lv['scroll']) + ",")
        lines.append("        'rows': (")
        for row in lv['rows']:
            lines.append("            " + repr("".join(row)) + ",")
        lines.append("        ),")
        lines.append("    },")
    lines.append(")")
    lines.append("")
    with open(path, 'w') as f:
        f.write("\n".join(lines))


def blank_level(width=LVL_W_DEFAULT):
    rows = [[' '] * width for _ in range(ROWS)]
    rows[ROWS - 1] = ['#'] * width
    rows[ROWS - 2][0] = 'S'
    return {'rows': rows, 'scroll': 0}


# ── File I/O — campaigns ──────────────────────────────────────────────────────

def load_campaigns():
    """Read _REGISTRY from campaigns.py. Returns list of dicts."""
    if not os.path.exists(CAMPAIGNS_PATH):
        return []
    with open(CAMPAIGNS_PATH) as f:
        src = f.read()
    ns = {}
    exec(src, ns)
    result = []
    palette_map = {name: col for name, col in DEPLOY_PALETTE}
    for row in ns.get('_REGISTRY', []):
        label, color_name, levels_file = row[0], row[1], row[2]
        result.append({
            'label':       label,
            'color_name':  color_name,
            'color':       palette_map.get(color_name, (255, 0, 200)),
            'levels_file': levels_file,
        })
    return result


def save_campaigns(campaigns):
    """Write campaigns.py and update the managed block in deploy.sh."""
    _write_campaigns_py(campaigns)
    _update_deploy_sh(campaigns)


def _write_campaigns_py(campaigns):
    lines = [
        "# games/platformer/campaigns.py",
        "# Managed by tools/screen_editor.py — do not edit by hand.",
        "# Use the CAMPAIGNS panel in the screen editor to add or remove campaigns.",
        "#",
        "# _REGISTRY is the authoritative list read and written by the editor.",
        "# ENTRIES is consumed by games/launcher/game.py at boot.",
        "#",
        "# Each _REGISTRY row: [label, color_name, levels_module_basename]",
        "",
        "_REGISTRY = [",
    ]
    for c in campaigns:
        lines.append("    ['" + c['label'] + "', '" + c['color_name'] + "', '" + c['levels_file'] + "'],")
    lines += [
        "]",
        "",
        "from lib.engine.colors import MAGENTA, CYAN, YELLOW, GREEN, ORANGE, PURPLE, RED",
        "",
        "_COLORS = {",
        "    'MAGENTA': MAGENTA, 'CYAN': CYAN, 'YELLOW': YELLOW, 'GREEN': GREEN,",
        "    'ORANGE': ORANGE, 'PURPLE': PURPLE, 'RED': RED,",
        "}",
        "",
        "",
        "def _make_factory(mod_name):",
        "    def _factory(hal):",
        "        from games.platformer.game import PlatformerGame",
        "        _ns = {}",
        "        exec('from games.platformer.' + mod_name + ' import LEVELS as _L', _ns)",
        "        return PlatformerGame(hal, levels=_ns['_L'])",
        "    return _factory",
        "",
        "",
        "ENTRIES = [",
        "    (r[0], _COLORS.get(r[1], MAGENTA), _make_factory(r[2]))",
        "    for r in _REGISTRY",
        "]",
        "",
    ]
    with open(CAMPAIGNS_PATH, 'w') as f:
        f.write("\n".join(lines))


def _update_deploy_sh(campaigns):
    """Replace the managed block between BEGIN/END markers in deploy.sh."""
    if not os.path.exists(DEPLOY_SH_PATH):
        return
    with open(DEPLOY_SH_PATH) as f:
        text = f.read()

    begin = '# BEGIN_PLATFORMER_LEVELS\n'
    end   = '# END_PLATFORMER_LEVELS'
    b_idx = text.find(begin)
    e_idx = text.find(end)
    if b_idx == -1 or e_idx == -1:
        return   # markers not found — don't touch the file

    cp_lines = ['# BEGIN_PLATFORMER_LEVELS\n']
    for c in campaigns:
        cp_lines.append('cp_file games/platformer/' + c['levels_file'] + '.py\n')
    cp_lines.append('# END_PLATFORMER_LEVELS')

    new_text = text[:b_idx] + ''.join(cp_lines) + text[e_idx + len(end):]
    with open(DEPLOY_SH_PATH, 'w') as f:
        f.write(new_text)


# ── UI helper ─────────────────────────────────────────────────────────────────

def _btn(surf, rect, label, normal, hover, font, mouse, active=False, disabled=False):
    if disabled:
        pygame.draw.rect(surf, (28, 28, 40), rect, border_radius=4)
        pygame.draw.rect(surf, (50, 50, 70), rect, 1, border_radius=4)
        lbl = font.render(label, True, (55, 55, 75))
        surf.blit(lbl, lbl.get_rect(center=rect.center))
        return False
    hov = rect.collidepoint(mouse)
    bg  = BTN_ACT if active else (hover if hov else normal)
    pygame.draw.rect(surf, bg, rect, border_radius=4)
    pygame.draw.rect(surf, (80, 80, 120), rect, 1, border_radius=4)
    lbl = font.render(label, True, TEXT_C)
    surf.blit(lbl, lbl.get_rect(center=rect.center))
    return hov


# ── Editor ────────────────────────────────────────────────────────────────────

class Editor:
    def __init__(self, save_path, start_level=0):
        pygame.init()
        self.screen  = pygame.display.set_mode((WIN_W, WIN_H))
        pygame.display.set_caption("Platformer Level Editor")
        self.clock   = pygame.time.Clock()
        self.font    = pygame.font.SysFont("monospace", 12)
        self.font_b  = pygame.font.SysFont("monospace", 13, bold=True)

        self.save_path = save_path
        self.levels    = load_levels_from_file(save_path)
        self.level_idx = max(0, min(start_level, len(self.levels) - 1))
        self.sel_tile  = 1
        self.cam_col   = 0
        self.painting  = False
        self.erasing   = False
        self.dirty     = False

        # ── Deploy / campaign state ───────────────────────────────────────────
        self._mode             = 'edit'       # 'edit' or 'campaigns'
        self._campaigns        = load_campaigns()
        self._dep_label        = ''           # 2-char label being typed
        self._dep_label_focus  = False
        self._dep_color_idx    = 0
        self._dep_status       = ''           # feedback message
        self._dep_status_ok    = True

        # Button rects (rebuilt each draw)
        self._btn_prev    = None
        self._btn_next    = None
        self._btn_new     = None
        self._btn_del     = None
        self._btn_addcol  = None
        self._btn_remcol  = None
        self._btn_spdup   = None
        self._btn_spddn   = None
        self._btn_save    = None
        self._btn_camps   = None    # top-bar campaigns toggle
        self._tile_btns   = []
        # Campaign mode rects
        self._remove_btns  = []    # list of (rect, label)
        self._color_rects  = []    # list of (rect, palette_idx)
        self._label_rect   = None
        self._deploy_btn   = None
        self._back_btn     = None

    # ── Level accessors ───────────────────────────────────────────────────────

    @property
    def _level(self):
        return self.levels[self.level_idx]

    @property
    def rows(self):
        return self._level['rows']

    @property
    def level_w(self):
        return len(self.rows[0])

    @property
    def scroll_speed(self):
        return self._level.get('scroll', 0)

    def set_scroll(self, spd):
        self._level['scroll'] = max(0, spd)
        self.dirty = True

    # ── Grid helpers ──────────────────────────────────────────────────────────

    def screen_to_cell(self, sx, sy):
        if sy < GRID_Y or sx >= COLS * CELL:
            return None
        gc = sx // CELL
        gr = (sy - GRID_Y) // CELL
        if 0 <= gc < COLS and 0 <= gr < ROWS:
            lc = gc + self.cam_col
            if 0 <= lc < self.level_w:
                return (lc, gr)
        return None

    def paint(self, lc, gr, erase=False):
        ch = ' ' if erase else TILE_CHARS[self.sel_tile]
        if ch == 'S':
            for r in range(ROWS):
                for c in range(self.level_w):
                    if self.rows[r][c] == 'S':
                        self.rows[r][c] = ' '
        self.rows[gr][lc] = ch
        self.dirty = True

    def scroll_view(self, delta):
        max_cam = max(0, self.level_w - COLS)
        self.cam_col = max(0, min(self.cam_col + delta, max_cam))

    def add_col(self):
        for row in self.rows:
            row.append(' ')
        self.dirty = True

    def remove_col(self):
        if self.level_w <= COLS:
            return
        for row in self.rows:
            row.pop()
        self.cam_col = min(self.cam_col, self.level_w - COLS)
        self.dirty = True

    # ── Campaign management ───────────────────────────────────────────────────

    def _campaign_labels(self):
        return {c['label'] for c in self._campaigns}

    def _do_deploy(self):
        label      = self._dep_label
        color_name = DEPLOY_PALETTE[self._dep_color_idx][0]
        color      = DEPLOY_PALETTE[self._dep_color_idx][1]

        # Determine where to store the levels file on disk
        src = self.save_path
        if os.path.abspath(src) == os.path.abspath(DEFAULT_LEVELS_PATH):
            levels_file = 'levels'   # already in the right place
        else:
            levels_file = 'levels_' + label
            dst = os.path.join(PLATFORMER_DIR, levels_file + '.py')
            shutil.copy2(src, dst)

        self._campaigns.append({
            'label':       label,
            'color_name':  color_name,
            'color':       color,
            'levels_file': levels_file,
        })
        save_campaigns(self._campaigns)
        self._dep_status    = 'Deployed as "' + label + '" — ready to deploy.sh!'
        self._dep_status_ok = True
        self._dep_label     = ''

    def _do_remove(self, label):
        before = len(self._campaigns)
        self._campaigns = [c for c in self._campaigns if c['label'] != label]
        if len(self._campaigns) < before:
            save_campaigns(self._campaigns)
            self._dep_status    = 'Removed "' + label + '"'
            self._dep_status_ok = True

    # ── Draw ──────────────────────────────────────────────────────────────────

    def draw(self):
        mouse = pygame.mouse.get_pos()
        self.screen.fill((0, 0, 0))
        self._draw_top_bar(mouse)
        if self._mode == 'campaigns':
            self._draw_campaigns(mouse)
        else:
            self._draw_edit_grid(mouse)
            self._draw_panel(mouse)
        pygame.display.flip()

    # ── Top bar ───────────────────────────────────────────────────────────────

    def _draw_top_bar(self, mouse):
        surf = self.screen
        pygame.draw.rect(surf, (12, 12, 22), (0, 0, WIN_W, TOP_H))

        bh, by = 30, (TOP_H - 30) // 2
        self._btn_prev = pygame.Rect(6,   by, 34, bh)
        self._btn_next = pygame.Rect(44,  by, 34, bh)
        self._btn_new  = pygame.Rect(82,  by, 44, bh)
        self._btn_del  = pygame.Rect(130, by, 36, bh)

        _btn(surf, self._btn_prev, "<",   BTN_C, BTN_HV, self.font_b, mouse, disabled=self.level_idx == 0)
        _btn(surf, self._btn_next, ">",   BTN_C, BTN_HV, self.font_b, mouse, disabled=self.level_idx == len(self.levels) - 1)
        _btn(surf, self._btn_new,  "NEW", BTN_C, BTN_HV, self.font,   mouse)
        _btn(surf, self._btn_del,  "DEL", BTN_DEL, BTN_DEL_H, self.font, mouse, disabled=len(self.levels) == 1)

        title = "Level " + str(self.level_idx + 1) + " / " + str(len(self.levels))
        if self.dirty:
            title += " *"
        surf.blit(self.font_b.render(title, True, TEXT_C), (178, 9))
        surf.blit(self.font.render(os.path.basename(self.save_path), True, DIM_C), (178, 27))

        col_info = "col " + str(self.cam_col) + "-" + str(self.cam_col + COLS - 1) + " / " + str(self.level_w - 1)
        surf.blit(self.font.render(col_info, True, DIM_C), (340, 19))

        # Campaigns toggle button — right side of top bar
        self._btn_camps = pygame.Rect(WIN_W - 120, by, 112, bh)
        active = self._mode == 'campaigns'
        _btn(surf, self._btn_camps, "CAMPAIGNS", BTN_DEP if not active else BTN_ACT, BTN_DEP_H, self.font_b, mouse, active=active)

    # ── Edit mode: grid ───────────────────────────────────────────────────────

    def _draw_edit_grid(self, mouse):
        surf = self.screen
        pygame.draw.rect(surf, GRID_BG, (0, GRID_Y, COLS * CELL, ROWS * CELL))

        for sc in range(COLS):
            lc = sc + self.cam_col
            for gr in range(ROWS):
                x = sc * CELL
                y = GRID_Y + gr * CELL
                if 0 <= lc < self.level_w:
                    ch  = self.rows[gr][lc]
                    idx = TILE_CHARS.index(ch) if ch in TILE_CHARS else 0
                    col = TILES[idx][2]
                else:
                    col = (6, 6, 10)
                pygame.draw.rect(surf, col, (x + 1, y + 1, CELL - 2, CELL - 2), border_radius=4)

        for sc in range(COLS + 1):
            pygame.draw.line(surf, GRID_LINE, (sc * CELL, GRID_Y), (sc * CELL, GRID_Y + ROWS * CELL))
        for gr in range(ROWS + 1):
            pygame.draw.line(surf, GRID_LINE, (0, GRID_Y + gr * CELL), (COLS * CELL, GRID_Y + gr * CELL))

        for sc in range(COLS):
            lc = sc + self.cam_col
            if 0 <= lc < self.level_w:
                for gr in range(ROWS):
                    ch = self.rows[gr][lc]
                    if ch != ' ':
                        lbl = self.font_b.render(ch, True, (220, 220, 220))
                        surf.blit(lbl, (sc * CELL + CELL // 2 - lbl.get_width() // 2,
                                        GRID_Y + gr * CELL + CELL // 2 - lbl.get_height() // 2))

        for sc in range(COLS):
            lc = sc + self.cam_col
            if lc % 4 == 0:
                n = self.font.render(str(lc), True, (55, 55, 85))
                surf.blit(n, (sc * CELL + 2, GRID_Y + ROWS * CELL - n.get_height() - 2))

        hcell = self.screen_to_cell(*mouse)
        if hcell is not None:
            hsc = hcell[0] - self.cam_col
            pygame.draw.rect(surf, HOVER_BDR,
                             (hsc * CELL + 1, GRID_Y + hcell[1] * CELL + 1, CELL - 2, CELL - 2),
                             2, border_radius=4)

        if self.scroll_speed > 0:
            pygame.draw.rect(surf, SCROLL_HI, (0, GRID_Y + ROWS * CELL, min(self.scroll_speed * 4, COLS * CELL), 4))

    # ── Edit mode: right panel ────────────────────────────────────────────────

    def _draw_panel(self, mouse):
        surf = self.screen
        px   = COLS * CELL
        pygame.draw.rect(surf, PANEL_BG, (px, 0, PANEL_W, WIN_H))
        pygame.draw.line(surf, (50, 50, 80), (px, 0), (px, WIN_H))

        cy = 12

        surf.blit(self.font_b.render("Tiles", True, TEXT_C), (px + 10, cy))
        cy += 20
        self._tile_btns = []
        for i, (ch, label, col) in enumerate(TILES):
            rect   = pygame.Rect(px + 6, cy, PANEL_W - 12, 26)
            active = (i == self.sel_tile)
            _btn(surf, rect, str(i + 1) + "  " + label, BTN_C, BTN_HV, self.font, mouse, active)
            swatch = pygame.Rect(px + PANEL_W - 28, cy + 3, 20, 20)
            pygame.draw.rect(surf, col, swatch, border_radius=3)
            if active:
                pygame.draw.rect(surf, SEL_BDR, swatch, 2, border_radius=3)
            self._tile_btns.append(rect)
            cy += 29

        cy += 6
        pygame.draw.line(surf, (50, 50, 80), (px + 6, cy), (px + PANEL_W - 6, cy))
        cy += 8
        surf.blit(self.font_b.render("Width: " + str(self.level_w), True, TEXT_C), (px + 8, cy))
        cy += 18
        half = (PANEL_W - 18) // 2
        self._btn_addcol = pygame.Rect(px + 6,            cy, half, 26)
        self._btn_remcol = pygame.Rect(px + 6 + half + 6, cy, half, 26)
        _btn(surf, self._btn_addcol, "+COL", BTN_ADD, BTN_ADD_H, self.font_b, mouse)
        _btn(surf, self._btn_remcol, "-COL", BTN_REM, BTN_REM_H, self.font_b, mouse, disabled=self.level_w <= COLS)
        cy += 32

        cy += 6
        pygame.draw.line(surf, (50, 50, 80), (px + 6, cy), (px + PANEL_W - 6, cy))
        cy += 8
        spd = self.scroll_speed
        spd_c = SCROLL_HI if spd > 0 else TEXT_C
        mode_lbl = " (auto)" if spd > 0 else " (off)"
        surf.blit(self.font_b.render("Scroll: " + str(spd) + mode_lbl, True, spd_c), (px + 8, cy))
        cy += 18
        self._btn_spdup = pygame.Rect(px + 6,            cy, half, 26)
        self._btn_spddn = pygame.Rect(px + 6 + half + 6, cy, half, 26)
        _btn(surf, self._btn_spdup, "SPD+", BTN_SPD, BTN_SPD_H, self.font_b, mouse)
        _btn(surf, self._btn_spddn, "SPD-", BTN_SPD, BTN_SPD_H, self.font_b, mouse, disabled=spd == 0)
        cy += 32
        if spd > 0:
            surf.blit(self.font.render("Jump-only mode", True, SCROLL_HI), (px + 8, cy))
            cy += 14

        cy += 4
        pygame.draw.line(surf, (50, 50, 80), (px + 6, cy), (px + PANEL_W - 6, cy))
        cy += 8
        self._btn_save = pygame.Rect(px + 6, cy, PANEL_W - 12, 28)
        _btn(surf, self._btn_save, "SAVE  (S)", BTN_SAV_H if self.dirty else BTN_SAVE, BTN_SAV_H, self.font_b, mouse)
        cy += 36

        for line in ("Paint: left-click", "Erase: right-click", "Scroll: wheel / arrows", "Levels: PgUp / PgDn"):
            surf.blit(self.font.render(line, True, DIM_C), (px + 8, cy))
            cy += 15

    # ── Campaigns mode ────────────────────────────────────────────────────────

    def _draw_campaigns(self, mouse):
        surf = self.screen
        ax, ay = 0, GRID_Y
        aw     = WIN_W

        pygame.draw.rect(surf, DEPLOY_BG, (ax, ay, aw, WIN_H - ay))

        cy = ay + 16

        # Title
        surf.blit(self.font_b.render("Manage Platformer Campaigns", True, (180, 180, 255)), (ax + 20, cy))
        cy += 22
        surf.blit(self.font.render("Changes are written to campaigns.py and deploy.sh immediately.", True, DIM_C), (ax + 20, cy))
        cy += 20
        pygame.draw.line(surf, (50, 50, 90), (ax + 10, cy), (ax + aw - 10, cy))
        cy += 14

        # ── Deployed list ─────────────────────────────────────────────────────
        surf.blit(self.font_b.render("Currently in the launcher carousel:", True, TEXT_C), (ax + 20, cy))
        cy += 20

        self._remove_btns = []
        if self._campaigns:
            for camp in self._campaigns:
                pygame.draw.rect(surf, (20, 20, 40), (ax + 18, cy, aw - 36, 34), border_radius=4)
                lbl_s = self.font_b.render('[' + camp['label'] + ']', True, camp['color'])
                surf.blit(lbl_s, (ax + 28, cy + 9))
                pygame.draw.rect(surf, camp['color'], (ax + 72, cy + 7, 20, 20), border_radius=3)
                fname = camp['levels_file'] + '.py'
                surf.blit(self.font.render(fname, True, TEXT_C), (ax + 100, cy + 10))
                rem = pygame.Rect(aw - 110, cy + 4, 90, 26)
                _btn(surf, rem, "REMOVE", BTN_DEL, BTN_DEL_H, self.font, mouse)
                self._remove_btns.append((rem, camp['label']))
                cy += 40
        else:
            surf.blit(self.font.render("No campaigns deployed yet.", True, DIM_C), (ax + 28, cy + 6))
            cy += 30

        cy += 6
        pygame.draw.line(surf, (50, 50, 90), (ax + 10, cy), (ax + aw - 10, cy))
        cy += 14

        # ── Add new campaign ──────────────────────────────────────────────────
        surf.blit(self.font_b.render("Add current file as a new campaign:", True, TEXT_C), (ax + 20, cy))
        cy += 20

        fname = os.path.basename(self.save_path)
        surf.blit(self.font.render("File:  " + fname, True, DIM_C), (ax + 28, cy))
        cy += 20

        # Label input
        surf.blit(self.font.render("Label (2 chars, A-Z):", True, TEXT_C), (ax + 28, cy + 7))
        self._label_rect = pygame.Rect(ax + 210, cy, 64, 30)
        pygame.draw.rect(surf, (25, 25, 50), self._label_rect, border_radius=4)
        border_c = (150, 150, 255) if self._dep_label_focus else (70, 70, 110)
        pygame.draw.rect(surf, border_c, self._label_rect, 2, border_radius=4)
        cursor = '_' if self._dep_label_focus and len(self._dep_label) < 2 else ''
        surf.blit(self.font_b.render(self._dep_label + cursor, True, (255, 255, 100)),
                  (self._label_rect.x + 8, self._label_rect.y + 7))
        cy += 38

        # Colour picker
        surf.blit(self.font.render("Colour:", True, TEXT_C), (ax + 28, cy + 10))
        self._color_rects = []
        for i, (cname, cval) in enumerate(DEPLOY_PALETTE):
            cr = pygame.Rect(ax + 100 + i * 42, cy, 36, 36)
            pygame.draw.rect(surf, cval, cr, border_radius=5)
            if i == self._dep_color_idx:
                pygame.draw.rect(surf, (255, 255, 100), cr, 2, border_radius=5)
            elif cr.collidepoint(mouse):
                pygame.draw.rect(surf, (200, 200, 200), cr, 1, border_radius=5)
            self._color_rects.append((cr, i))
            name_s = self.font.render(cname[:3], True, (150, 150, 150))
            surf.blit(name_s, (cr.x + cr.width // 2 - name_s.get_width() // 2, cr.y + cr.height + 2))
        cy += 56

        # Validation
        used   = self._campaign_labels()
        ok     = len(self._dep_label) == 2 and self._dep_label not in used
        if len(self._dep_label) < 2:
            warn = "Type a 2-letter label first"
        elif self._dep_label in used:
            warn = 'Label "' + self._dep_label + '" is already deployed'
        else:
            warn = ''
        if warn:
            surf.blit(self.font.render(warn, True, WARN_C), (ax + 28, cy))
            cy += 18

        self._deploy_btn = pygame.Rect(ax + 28, cy, 240, 34)
        _btn(surf, self._deploy_btn, "ADD TO CAROUSEL", BTN_SAVE, BTN_SAV_H, self.font_b, mouse, disabled=not ok)
        cy += 44

        # Status message
        if self._dep_status:
            sc = OK_C if self._dep_status_ok else WARN_C
            surf.blit(self.font_b.render(self._dep_status, True, sc), (ax + 28, cy))
            cy += 22

        pygame.draw.line(surf, (50, 50, 90), (ax + 10, cy), (ax + aw - 10, cy))
        cy += 14

        self._back_btn = pygame.Rect(ax + 28, cy, 140, 30)
        _btn(surf, self._back_btn, "\u2190 BACK TO EDITING", BTN_C, BTN_HV, self.font_b, mouse)

    # ── Event loop ────────────────────────────────────────────────────────────

    def run(self):
        while True:
            self.clock.tick(60)
            mouse = pygame.mouse.get_pos()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    if self.dirty:
                        print("Warning: unsaved changes — " + self.save_path)
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.MOUSEWHEEL:
                    if self._mode == 'edit':
                        self.scroll_view(-event.y)
                elif event.type == pygame.MOUSEBUTTONDOWN:
                    if event.button == 1:
                        self._on_lclick(mouse)
                    elif event.button == 3 and self._mode == 'edit':
                        cell = self.screen_to_cell(*mouse)
                        if cell:
                            self.paint(*cell, erase=True)
                            self.erasing = True
                elif event.type == pygame.MOUSEBUTTONUP:
                    self.painting = False
                    self.erasing  = False
                elif event.type == pygame.MOUSEMOTION:
                    if self._mode == 'edit':
                        if self.painting:
                            cell = self.screen_to_cell(*mouse)
                            if cell:
                                self.paint(*cell)
                        elif self.erasing:
                            cell = self.screen_to_cell(*mouse)
                            if cell:
                                self.paint(*cell, erase=True)
                elif event.type == pygame.KEYDOWN:
                    self._on_key(event.key)
                elif event.type == pygame.USEREVENT:
                    pygame.display.set_caption("Platformer Level Editor")
            self.draw()

    # ── Input routing ─────────────────────────────────────────────────────────

    def _on_lclick(self, mouse):
        # Top bar (always active)
        if self._btn_camps and self._btn_camps.collidepoint(mouse):
            self._mode = 'campaigns' if self._mode == 'edit' else 'edit'
            self._dep_status = ''
            return
        if self._btn_prev and self._btn_prev.collidepoint(mouse) and self.level_idx > 0:
            self.level_idx -= 1; self.cam_col = 0; return
        if self._btn_next and self._btn_next.collidepoint(mouse) and self.level_idx < len(self.levels) - 1:
            self.level_idx += 1; self.cam_col = 0; return
        if self._btn_new and self._btn_new.collidepoint(mouse):
            self.levels.append(blank_level())
            self.level_idx = len(self.levels) - 1
            self.cam_col = 0; self.dirty = True; return
        if self._btn_del and self._btn_del.collidepoint(mouse) and len(self.levels) > 1:
            self.levels.pop(self.level_idx)
            self.level_idx = min(self.level_idx, len(self.levels) - 1)
            self.cam_col = 0; self.dirty = True; return

        if self._mode == 'campaigns':
            self._on_lclick_campaigns(mouse)
        else:
            self._on_lclick_edit(mouse)

    def _on_lclick_edit(self, mouse):
        if self._btn_save and self._btn_save.collidepoint(mouse):
            self._save(); return
        if self._btn_addcol and self._btn_addcol.collidepoint(mouse):
            self.add_col(); return
        if self._btn_remcol and self._btn_remcol.collidepoint(mouse) and self.level_w > COLS:
            self.remove_col(); return
        if self._btn_spdup and self._btn_spdup.collidepoint(mouse):
            self.set_scroll(self.scroll_speed + 1); return
        if self._btn_spddn and self._btn_spddn.collidepoint(mouse) and self.scroll_speed > 0:
            self.set_scroll(self.scroll_speed - 1); return
        for i, rect in enumerate(self._tile_btns):
            if rect.collidepoint(mouse):
                self.sel_tile = i; return
        cell = self.screen_to_cell(*mouse)
        if cell:
            self.paint(*cell)
            self.painting = True

    def _on_lclick_campaigns(self, mouse):
        # Remove buttons
        for rect, label in self._remove_btns:
            if rect.collidepoint(mouse):
                self._do_remove(label); return
        # Color swatches
        for rect, idx in self._color_rects:
            if rect.collidepoint(mouse):
                self._dep_color_idx = idx; return
        # Label field focus
        if self._label_rect and self._label_rect.collidepoint(mouse):
            self._dep_label_focus = True; return
        else:
            self._dep_label_focus = False
        # Deploy button
        if self._deploy_btn and self._deploy_btn.collidepoint(mouse):
            used = self._campaign_labels()
            if len(self._dep_label) == 2 and self._dep_label not in used:
                self._do_deploy(); return
        # Back button
        if self._back_btn and self._back_btn.collidepoint(mouse):
            self._mode = 'edit'; return

    def _on_key(self, key):
        if self._mode == 'campaigns':
            self._on_key_campaigns(key)
        else:
            self._on_key_edit(key)

    def _on_key_edit(self, key):
        if key == pygame.K_s:
            self._save()
        elif key == pygame.K_LEFT:
            self.scroll_view(-1)
        elif key == pygame.K_RIGHT:
            self.scroll_view(1)
        elif key == pygame.K_PAGEUP and self.level_idx > 0:
            self.level_idx -= 1; self.cam_col = 0
        elif key == pygame.K_PAGEDOWN and self.level_idx < len(self.levels) - 1:
            self.level_idx += 1; self.cam_col = 0
        elif pygame.K_1 <= key <= pygame.K_6:
            self.sel_tile = key - pygame.K_1

    def _on_key_campaigns(self, key):
        if not self._dep_label_focus:
            if key == pygame.K_ESCAPE:
                self._mode = 'edit'
            return
        # Label text input: A-Z only, max 2 chars, backspace to delete
        if key == pygame.K_BACKSPACE:
            self._dep_label = self._dep_label[:-1]
        elif key == pygame.K_RETURN or key == pygame.K_ESCAPE:
            self._dep_label_focus = False
        elif len(self._dep_label) < 2:
            ch = pygame.key.name(key).upper()
            if len(ch) == 1 and ch.isalpha():
                self._dep_label += ch

    def _save(self):
        save_levels_to_file(self.levels, self.save_path)
        self.dirty = False
        pygame.display.set_caption("Platformer Level Editor — Saved!")
        pygame.time.set_timer(pygame.USEREVENT, 1500, loops=1)


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    save_path   = DEFAULT_LEVELS_PATH
    start_level = 0
    args = sys.argv[1:]
    i = 0
    while i < len(args):
        if args[i] in ("--file", "-f") and i + 1 < len(args):
            p = args[i + 1]
            save_path = p if os.path.isabs(p) else os.path.join(os.getcwd(), p)
            i += 2
        elif args[i] in ("--level", "-l") and i + 1 < len(args):
            start_level = int(args[i + 1])
            i += 2
        else:
            i += 1
    Editor(save_path=save_path, start_level=start_level).run()


if __name__ == "__main__":
    main()
